version: "3.9"
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - ./dev/.env.dev
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdbdata:/var/lib/postgresql/data

  drf:
    build: .
    container_name: drf
    command:  sh -c "sleep 5 && ./entrypoint.sh"
    env_file:
      - ./dev/.env.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  pgdbdata: null