version: "3.9"
services:
  pgdb:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  drf:
    build: .
    container_name: drf
    command: sh -c "sleep 5 && ./entrypoint.sh"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  pgdbdata: null