version: "3.9"

services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  drf:
    build: .
    container_name: drf
    command: make runserver
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: make celery-worker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: make celery-beat
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - drf

volumes:
  postgres_data:
  static_volume:
  media_volume: