version: "3.9"
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  drf:
    build: .
    container_name: drf
    command: sh -c "sleep 5 && make runserver"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: make celery-worker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: make celery-beat
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  pgdbdata: null