name: main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install docker and docker-compose
        uses: docker/setup-buildx-action@v2
        with:
          docker-version: '20.10.7'

      - name: Create .env file for tests
        run: echo "ENV_STAGE=${{ secrets.ENV_STAGE }}" > .env

      - name: Build, test, lint and clean up project
        run: make tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Connect to server and git pull
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            make deploy-project
          EOF